services:
  - type: web
    name: petstore-backend
    runtime: docker
    rootDir: backend
    branch: render-deploy
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: petstore-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: petstore-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: petstore-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: petstore-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: petstore-db
          property: password
      - key: CORS_ALLOWED_ORIGIN_PATTERNS
        value: https://*.onrender.com,http://localhost:5173,http://localhost:5174,http://localhost:5175
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080

  - type: web
    name: petstore-frontend
    runtime: docker
    rootDir: frontend
    branch: render-deploy
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        value: https://petstore-backend-4a0y.onrender.com

databases:
  - name: petstore-db
    databaseName: petstore
    user: petstore
    plan: free
    ipAllowList: []
