spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:petstore}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:petstore}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:petstore}}
spring.jpa.hibernate.ddl-auto=validate
