spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:petstore}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:petstore}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:petstore}}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.lumba.petstore: INFO
